//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkietaP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adre
    {
        public int id_adres { get; set; }
        public string miejscowosc { get; set; }
        public string ulica { get; set; }
        public string dom { get; set; }
        public string lokal { get; set; }
        public string kod_pocztowy { get; set; }
    }
}
