//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkietaP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class miejscowosc
    {
        public Nullable<int> id_woj { get; set; }
        public Nullable<int> id_pow { get; set; }
        public Nullable<int> id_gmi { get; set; }
        public int symbol { get; set; }
        public Nullable<int> symbol_pods { get; set; }
        public string nazwa { get; set; }
    }
}
