//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkietaP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class powiat_gmina
    {
        public Nullable<int> id_powiat_gmina { get; set; }
        public int id_woj { get; set; }
        public int id_pow { get; set; }
        public int id_gmi { get; set; }
        public Nullable<int> nazwa { get; set; }
        public Nullable<int> naz_dod { get; set; }
    }
}
