//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkietaP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pytanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pytanie()
        {
            this.opcjes = new HashSet<opcje>();
            this.wynik_bool = new HashSet<wynik_bool>();
        }
    
        public int id_pytanie { get; set; }
        public string tresc { get; set; }
        public Nullable<int> id_ankieta { get; set; }
        public Nullable<int> id_kategoria_pytania { get; set; }
    
        public virtual ankieta ankieta { get; set; }
        public virtual kategoria_pytania kategoria_pytania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opcje> opcjes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wynik_bool> wynik_bool { get; set; }
    }
}
