//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkietaP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wynik_lista
    {
        public int id_wynik_lista { get; set; }
        public Nullable<int> ilosc { get; set; }
        public Nullable<int> id_opcje { get; set; }
    
        public virtual opcje opcje { get; set; }
    }
}
