//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkietaP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wynik_bool
    {
        public int id_wynik_bool { get; set; }
        public Nullable<int> tak { get; set; }
        public Nullable<int> nie { get; set; }
        public Nullable<int> id_pytanie { get; set; }
    
        public virtual pytanie pytanie { get; set; }
    }
}
